language: node_js
node_js:
  - 9.11.2
addons:
  postgresql: "9.4"
services:
  - redis-server
  - postgresql
cache:
  bundler: true
  yarn: true
  directories:
    - /home/travis/.rvm/
    - ~/.cache
before_install:
  - gem install bundler
  - bundle install
install:
  - yarn add cypress
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - bin/rails server &
  - bundle exec rake assets:precompile
  - sleep 10
  - RAILS_ENV=test bundle exec rake db:schema:load
  - RAILS_ENV=test bundle exec rake your_seed
script:
  - $(yarn bin)/cypress run --record
  - bundle exec rspec spec/controllers spec/models spec/jobs