language: node_js
node_js:
  - 9.11.1
services:
  - postgresql
before_install:
  - gem install bundler
  - bundle install
cache:
  yarn: true
  bundler: true
  directories:
    - ~/.npm
    - ~/.cache
    - "node_modules"
install:
  - npm install
before_script:
  - rails server &
  - psql -c 'create database travis_ci_test;' -U postgres
  - rails db:migrate
  - RAILS_ENV=test bundle exec rake db:seed
script:
  - $(npm bin)/cypress run